name: PR

on:
  pull_request:
    branches: [development]

jobs:
  typecheck:
    uses: ./.github/workflows/typecheck.yml

  format:
    uses: ./.github/workflows/format-check.yml

  lint:
    uses: ./.github/workflows/lint.yml

  build-check:
    uses: ./.github/workflows/build-check.yml
